language: cpp

matrix:
  include:

    - os: osx
      osx_image: xcode9.1
      compiler: clang
      env: CMAKE_CONFIGURATION=release BUILD_DIR=build

    - os: osx
      osx_image: xcode9.1
      compiler: clang
      env: CMAKE_CONFIGURATION=debug BUILD_DIR=build-debug

    - os: linux
      env: CMAKE_CONFIGURATION=release BUILD_DIR=build CXX=g++-5 CC=gcc-5
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - cmake
          - g++-5

    - os: linux
      env: CMAKE_CONFIGURATION=debug BUILD_DIR=build-debug CXX=g++-5 CC=gcc-5
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - cmake
          - g++-5

    - os: linux
      env: CMAKE_CONFIGURATION=release BUILD_DIR=build CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - cmake
          - g++-5

    - os: linux
      env: CMAKE_CONFIGURATION=debug BUILD_DIR=build-debug CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          sources:
          - llvm-toolchain-precise-3.8
          packages:
          - cmake
          - clang-3.8

before_script:
  - ./configure
  - ./configure $CMAKE_CONFIGURATION

script:
  - cmake --build $BUILD_DIR
  - cmake --build $BUILD_DIR --target test
